

theme: jekyll-theme-cayman
title: Bending Nature
subtitle: Growing Naturally 
email: Isaac.bryce@outlook.com
description: Bending Nature is a project aimed at providing simple gardening reminders based of location and season. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bendingnature.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Spare_Time_Dev
github_username:  IsaacBryce
facebook_username: sparetimedev
author: Isaac Bryce